### PR TITLE
added navigation bar 

### PR DESCRIPTION
**Pull request by chaitanyakatore**
fixes the issues #7 
added navigation bar to the site
add under hacktoberfest-accepted

### CODE REVIEW

**Comment by chaitanyakatore** [comment]
Screenshot 2023-10-06 at 11 37 07 PM

 -  on my local side it is working good
 - please check this is good without making Any issue to server side

**Comment by ankitrout2903** [comment]
> please check this is good without making Any issue to server side 
> on my local side it is working good
> 



Bro again node modules 😑😑😑

**Comment by chaitanyakatore** [comment]
- I so sorry now check 
- please will you change the link app In the app section

**Comment by ankitrout2903** [comment]
Great pr bro

**Comment by chaitanyakatore** [comment]
thank you so much for guiding me really appreciate

**Pull request merged**
