### PR TITLE
Register button on the Login Screen #21 +The whole flow is breaking the container is not taking proper width #25

### PR DESCRIPTION
**Pull request by GouravKumar13**
Ui changes have been done

### CODE REVIEW

**Comment by ankitrout2903** [comment]
> Ui changes have been done 

Buddy can you please attach a screenshot of the fix I will merge it once it reaches my expectations.

**Comment by GouravKumar13** [comment]
image

**Comment by GouravKumar13** [comment]
image

**Comment by GouravKumar13** [comment]
@ankitrout2903  i have fixed both the issues you can check

**Comment by ankitrout2903** [comment]
> @ankitrout2903  i have fixed both the issues you can check

Buddy can I get a screenshot from you

**Comment by GouravKumar13** [comment]
@ankitrout2903 I have attached the screenshot  above

**Pull request merged**
